# Generated by Django 4.2.3 on 2023-08-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_alter_user_tc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tc',
        ),
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
